### ISSUE TITLE
Should not stop the build if no error

### ISSUE THREAD

**Issue by jnizet** [caitp/gulp-ddescribe-iit#10]
Beware: I don't know much about gulp.

Here's my problem: when adding the ddescribe-iit task to the dependencies of a task that starts a server, the server doesn't start and the build stops:

```
gulp.task('ddescribe-iit', function() {
  return gulp.src([path.join(conf.paths.src, 'app/**/*.spec.js')]).pipe(ddescribeIit());
});
gulp.task('build', ['html', 'fonts', 'ddescribe-iit', 'other']);
gulp.task('serve:e2e-dist', ['build'], function () {
    startServer([conf.paths.dist]);
});
```

If I run `gulp serve:dist` and `'ddescribe-iit'` is removed from the list of task dependencies of the build task, everything works correctly: the build is done, the server starts, and the build never ends until I press Ctrl-C.
If If leave `'ddescribe-iit'` int the list of task dependencies of the build task, the build is done, but the gulp stops immediately after, without letting the server start, and with no error message from ddescribe-iit.

Is it a bug of ddescribe-iit, or is there something I should do to prevent that to happen? If the latter, it might be worth mentioning it in the README.

**Comment by caitp** [comment]
Post a reproduction and we'll find out

**Comment by jnizet** [comment]
Fair enough. Here it goes:

## gulpfile.js

```
var gulp = require('gulp');
var connect = require('connect');
var ddescribeIit = require('gulp-ddescribe-iit');

gulp.task('ddescribe-iit', function() {
  return gulp.src('**/*.spec.js').pipe(ddescribeIit());
});

function startServer() {
  var app = connect();
  app.listen(3000);
}

gulp.task('serve', [], function () {
  startServer();
});

gulp.task('serve:dist', ['ddescribe-iit'], function () {
  startServer();
});
```

## package.json

```
{
  "name": "repro",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "connect": "^3.4.0",
    "gulp": "^3.9.0",
    "gulp-ddescribe-iit": "^1.2.2"
  }
}
```

## Steps to reproduce:
- `gulp serve`: the build never ends: it starts a server and listens until Ctrl-C: OK
- `gulp serve:dist`: the build executes ddescribe-iit and stops immediately: KO: it should start a server just as `gulp serve` does

**Comment by caitp** [comment]
I mean like, a full project. Do you have code on github where this is failing?

**Comment by caitp** [comment]
Yeah, I see the issue. I'll publish a fix in a moment

**Comment by caitp** [comment]
Woops, didn't mean to close that, I'll let you verify the fix first. It will be on npm as soon as travis finishes

**Comment by caitp** [comment]
version 1.3.0 is published, it should fix this for you

**Comment by jnizet** [comment]
Great. Works fine :+1: 
Thanks for the ultra-quick fix.

**Comment by caitp** [comment]
great, closing this then, enjoy
